[build-system]
requires = [ "setuptools",]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.9"
name = "maynard"
readme = "README.md"
dynamic = [ "version",]
license = {file = "LICENSE"}
description = "A Kedro-based nowcasting tool for the modern economy."
authors = [
    { name = "Elżbieta Jowik", email = "jowik.elzbieta@gmail.com" },
    { name = "Agnieszka Jastrzębska", email = "agnieszka.jastrzebska.mini@pw.edu.pl" },
    { name = "Michał Gamrot", email = "gamrot@gmail.com" }
]
maintainers = [
    { name = "Elżbieta Jowik", email = "jowik.elzbieta@gmail.com" }
]
dependencies = [
        "kedro==0.19.9",
        "kedro-viz==10.1.0",
        "kedro-datasets==6.0.0",
        "bottleneck==1.4.0",
        "numpy==1.26.4",
        "pmdarima==2.0.4",
        "linear-tree==0.3.5",
        "mifs @ git+https://github.com/jowike/mifs.git@maynard",
        "numpy==1.26.4",
        "seaborn==0.12.2",
        "xlsxwriter==3.2.2",
        "openpyxl==3.1.5",
        "pyarrow==18.0.0",
        "fastparquet==2024.5.0",
        "kaleido==0.2.1",
        "diskcache==5.6.3",
        "shap==0.47.0",
        "rpy2==3.5.11",
        "scipy==1.11.4",
        "typer==0.16.0"
    ]


[project.scripts]
maynard = "maynard.__main__:app"

[tool.kedro]
package_name = "maynard"
project_name = "maynard"
kedro_init_version = "0.19.9"
tools = "['Kedro Viz']"
example_pipeline = "True"
source_dir = "src"

[tool.setuptools.dynamic.version]
attr = "maynard.__version__"

[tool.setuptools.packages.find]
where = [ "src",]
namespaces = false

[tool.kedro_telemetry]
project_id = "maynard"

[tool.setuptools.package-data]
maynard = [
    "conf/**/*",
    "data/**/*",
    "pyproject.toml",
    "*.py"
]