from kedro.pipeline import Pipeline, node, pipeline

from .nodes import (
    prepare_vintage_data,
    suggest_spec,
    harmonize_ragged_edges,
    transform_time_series,
    test_variance,
    test_stationarity,
    apply_series_selection,
    estimate_ml_node,
    estimate_arima_node,
    estimate_var_node,
    collect_results
)


def create_pipeline(**kwargs) -> Pipeline:
    return pipeline(
        [
            node(
                func=prepare_vintage_data,
                inputs=[
                    "revision_history",
                    "params:options",
                    "params:spec_options",
                ],
                outputs=["vintage_data", "spec"],
                name="prepare_vintage_data",
            ),
            node(
                func=harmonize_ragged_edges,
                inputs=[
                    "vintage_data",
                    "spec",
                    "params:options",
                ],
                outputs="ragged_edge_aligned",
                name="harmonize_ragged_edges",
            ),
            node(
                func=transform_time_series,
                inputs=[
                    "ragged_edge_aligned",
                    "spec",
                    "params:options",
                ],
                outputs=["transformed_aligned", "raw_aligned"],
                name="transform_time_series",
            ),
            node(
                func=test_variance,
                inputs=[
                    "transformed_aligned",
                    "spec",
                    "params:options",
                ],
                outputs="filtered_by_variance",
                name="test_variance",
            ),
            node(
                func=test_stationarity,
                inputs=[
                    "filtered_by_variance",
                    "spec",
                    "params:options",
                ],
                outputs="filtered_stationary",
                name="test_stationarity",
            ),
            node(
                func=apply_series_selection,
                inputs=[
                    "filtered_stationary",
                    "spec",
                    "params:options",
                ],
                outputs="final_selected_features",
                name="select_series",
            ),
            node(
                func=estimate_ml_node,
                inputs=[
                    "final_selected_features",
                    "raw_aligned",
                    "spec",
                    "params:options",
                ],
                outputs="ml_estimation_results",
                name="estimate_ml_models",
            ),
            node(
                func=estimate_arima_node,
                inputs=[
                    "final_selected_features",
                    "raw_aligned",
                    "spec",
                    "params:options",
                ],
                outputs="ar_estimation_results",
                name="estimate_arima",
            ),
            node(
                func=estimate_var_node,
                inputs=[
                    "final_selected_features",
                    "raw_aligned",
                    "spec",
                    "params:options",
                ],
                outputs="var_estimation_results",
                name="estimate_var",
            ),
            node(
                func=collect_results,
                inputs=[
                    "spec",
                    "revision_history",
                    "raw_aligned",
                    "params:options",
                    "ar_estimation_results",
                    "ml_estimation_results",
                    "var_estimation_results"
                ],
                outputs="results",
                name="collect_results",
            ),
        ]
    )
